-- FitTrack Pro remote DB dump
-- Source database: HfVccHhCtMME6GEsJxyASd
-- Created at: 2026-05-14T04:37:30.628Z
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `__drizzle_migrations`;
CREATE TABLE `__drizzle_migrations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `hash` text NOT NULL,
  `created_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=237214;

INSERT INTO `__drizzle_migrations` (`id`, `hash`, `created_at`) VALUES
(1, '814a08e40d7fc2bcfd458759d18319198ca8ae394f2fa15617a78678e9c9c93b', 1778464845554);

DROP TABLE IF EXISTS `body_weights`;
CREATE TABLE `body_weights` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `weightKg` float NOT NULL,
  `bodyFatPct` float DEFAULT NULL,
  `muscleMassPct` float DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `recordedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=60001;

DROP TABLE IF EXISTS `exercise_favorites`;
CREATE TABLE `exercise_favorites` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `exerciseId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `user_exercise_unique` (`userId`,`exerciseId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

DROP TABLE IF EXISTS `exercise_goals`;
CREATE TABLE `exercise_goals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `exerciseId` int NOT NULL,
  `targetWeightKg` float DEFAULT NULL,
  `targetReps` int DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=60001;

DROP TABLE IF EXISTS `exercises`;
CREATE TABLE `exercises` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `nameKo` varchar(200) NOT NULL,
  `bodyPart` enum('chest','back','shoulders','arms','legs','abs','glutes','cardio','stretching','full_body') NOT NULL,
  `equipment` enum('barbell','dumbbell','machine','cable','bodyweight','kettlebell','resistance_band','none') NOT NULL,
  `category` enum('strength','hypertrophy','endurance','flexibility','cardio') NOT NULL,
  `difficulty` enum('beginner','intermediate','advanced') NOT NULL,
  `description` text DEFAULT NULL,
  `descriptionKo` text DEFAULT NULL,
  `primaryMuscles` json NOT NULL,
  `secondaryMuscles` json NOT NULL,
  `gifUrl` text DEFAULT NULL,
  `secondaryImages` json DEFAULT NULL,
  `instructions` json NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `instructionsKo` json DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=270001;

INSERT INTO `exercises` (`id`, `name`, `nameKo`, `bodyPart`, `equipment`, `category`, `difficulty`, `description`, `descriptionKo`, `primaryMuscles`, `secondaryMuscles`, `gifUrl`, `secondaryImages`, `instructions`, `createdAt`, `instructionsKo`) VALUES
(240001, 'Barbell Bench Press', '바벨 벤치프레스', 'chest', 'barbell', 'strength', 'intermediate', 'The classic chest exercise using a barbell on a flat bench.', '플랫 벤치에서 바벨을 이용한 클래식 가슴 운동입니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\",\"triceps\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip%2F1.jpg\"]', '[\"Lie flat on bench\",\"Grip bar slightly wider than shoulder width\",\"Lower bar to chest\",\"Press bar up explosively\"]', '2026-05-11 19:33:48', '[\"플랫 벤치에 등을 대고 눕습니다.\",\"바를 어깨너비보다 약간 넓게 잡습니다.\",\"바를 가슴 중앙까지 천천히 내립니다.\",\"가슴 근육을 수축하며 바를 힘차게 밀어 올립니다.\",\"팔꿈치를 완전히 펴지 않도록 주의하며 반복합니다.\"]'),
(240002, 'Incline Barbell Bench Press', '인클라인 바벨 벤치프레스', 'chest', 'barbell', 'hypertrophy', 'intermediate', 'Targets the upper chest with an inclined bench.', '인클라인 벤치를 사용하여 상부 가슴을 집중적으로 자극합니다.', '[\"upper pectoralis major\"]', '[\"anterior deltoid\",\"triceps\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip%2F1.jpg\"]', '[\"Set bench to 30-45 degrees\",\"Grip bar wider than shoulder width\",\"Lower to upper chest\",\"Press up and slightly back\"]', '2026-05-11 19:33:48', '[\"벤치를 30~45도로 기울여 설정합니다.\",\"어깨너비보다 넓게 바를 잡습니다.\",\"바를 상부 가슴까지 천천히 내립니다.\",\"상부 가슴을 수축하며 위로 밀어 올립니다.\",\"동작 내내 허리가 과도하게 아치되지 않도록 합니다.\"]'),
(240003, 'Dumbbell Bench Press', '덤벨 벤치프레스', 'chest', 'dumbbell', 'hypertrophy', 'beginner', 'Chest press using dumbbells for greater range of motion.', '덤벨을 사용하여 더 넓은 가동 범위로 가슴을 자극합니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\",\"triceps\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press%2F1.jpg\"]', '[\"Lie on bench with dumbbells\",\"Lower dumbbells to chest level\",\"Press up while keeping control\",\"Squeeze chest at top\"]', '2026-05-11 19:33:48', '[\"양손에 덤벨을 들고 플랫 벤치에 눕습니다.\",\"덤벨을 가슴 옆으로 천천히 내립니다.\",\"가슴 근육을 수축하며 덤벨을 위로 밀어 올립니다.\",\"정점에서 덤벨을 살짝 모아 가슴을 더 수축합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240004, 'Dumbbell Flyes', '덤벨 플라이', 'chest', 'dumbbell', 'hypertrophy', 'beginner', 'Isolation exercise for chest using a wide arc motion.', '넓은 호 동작으로 가슴을 고립시키는 운동입니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes%2F1.jpg\"]', '[\"Lie on bench with dumbbells\",\"Open arms wide in arc\",\"Feel chest stretch\",\"Bring arms back together\"]', '2026-05-11 19:33:48', '[\"양손에 덤벨을 들고 플랫 벤치에 눕습니다.\",\"팔꿈치를 약간 구부린 상태로 팔을 옆으로 넓게 벌립니다.\",\"가슴 근육이 충분히 늘어나는 것을 느낍니다.\",\"가슴 근육을 수축하며 팔을 다시 모읍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240005, 'Cable Crossover', '케이블 크로스오버', 'chest', 'cable', 'hypertrophy', 'intermediate', 'Cable exercise for chest isolation and peak contraction.', '케이블을 이용한 가슴 고립 및 피크 수축 운동입니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover%2F1.jpg\"]', '[\"Stand between cable stations\",\"Pull cables down and across\",\"Squeeze chest at bottom\",\"Slowly return to start\"]', '2026-05-11 19:33:49', '[\"케이블 머신 중앙에 서서 양손으로 케이블을 잡습니다.\",\"상체를 약간 앞으로 기울입니다.\",\"케이블을 아래로 당기며 양손을 모읍니다.\",\"가슴 근육이 완전히 수축되는 것을 느낍니다.\",\"천천히 원래 위치로 돌아가며 반복합니다.\"]'),
(240006, 'Push-Up', '푸시업', 'chest', 'bodyweight', 'endurance', 'beginner', 'Classic bodyweight chest exercise.', '클래식 맨몸 가슴 운동입니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\",\"triceps\",\"core\"]', NULL, '[]', '[\"Start in plank position\",\"Lower chest to floor\",\"Push back up\",\"Keep core tight throughout\"]', '2026-05-11 19:33:49', '[\"손을 어깨너비로 벌리고 플랭크 자세를 취합니다.\",\"몸을 일직선으로 유지하며 가슴이 바닥에 닿을 때까지 내립니다.\",\"가슴 근육을 수축하며 몸을 밀어 올립니다.\",\"동작 내내 코어를 단단히 유지합니다.\",\"목표 횟수만큼 반복합니다.\"]'),
(240007, 'Decline Bench Press', '디클라인 벤치프레스', 'chest', 'barbell', 'strength', 'intermediate', 'Targets the lower chest with a declined bench.', '디클라인 벤치로 하부 가슴을 집중 자극합니다.', '[\"lower pectoralis major\"]', '[\"triceps\"]', NULL, '[]', '[\"Set bench to -15 to -30 degrees\",\"Secure feet\",\"Lower bar to lower chest\",\"Press up powerfully\"]', '2026-05-11 19:33:49', '[\"벤치를 -15~-30도로 기울이고 발을 고정합니다.\",\"어깨너비보다 넓게 바를 잡습니다.\",\"바를 하부 가슴까지 천천히 내립니다.\",\"하부 가슴을 수축하며 바를 힘차게 밀어 올립니다.\",\"천천히 내리며 반복합니다.\"]'),
(240008, 'Chest Dips', '체스트 딥스', 'chest', 'bodyweight', 'strength', 'intermediate', 'Dips leaning forward to emphasize chest.', '앞으로 기울여 가슴을 강조하는 딥스 운동입니다.', '[\"lower pectoralis major\"]', '[\"triceps\",\"anterior deltoid\"]', NULL, '[]', '[\"Grip parallel bars\",\"Lean forward slightly\",\"Lower until chest stretches\",\"Push back up\"]', '2026-05-11 19:33:49', '[\"평행봉을 양손으로 잡고 몸을 들어 올립니다.\",\"상체를 약간 앞으로 기울입니다.\",\"가슴이 충분히 늘어날 때까지 천천히 내려갑니다.\",\"가슴 근육을 수축하며 다시 밀어 올립니다.\",\"천천히 내리며 반복합니다.\"]'),
(240009, 'Deadlift', '데드리프트', 'back', 'barbell', 'strength', 'advanced', 'The king of all exercises targeting the entire posterior chain.', '전체 후면 근육을 자극하는 운동의 왕입니다.', '[\"erector spinae\",\"glutes\"]', '[\"hamstrings\",\"trapezius\",\"rhomboids\",\"lats\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift%2F1.jpg\"]', '[\"Stand with bar over feet\",\"Hip hinge to grip bar\",\"Brace core and lift\",\"Lock out hips at top\"]', '2026-05-11 19:33:50', '[\"발을 어깨너비로 벌리고 바벨 앞에 섭니다.\",\"엉덩이를 뒤로 빼며 상체를 숙여 바를 잡습니다.\",\"코어와 등을 단단히 유지하며 바를 들어 올립니다.\",\"엉덩이를 앞으로 밀며 완전히 서서 동작을 마무리합니다.\",\"천천히 바를 내리며 반복합니다.\"]'),
(240010, 'Pull-Up', '풀업', 'back', 'bodyweight', 'strength', 'intermediate', 'Classic upper body pulling exercise.', '클래식 상체 당기기 운동입니다.', '[\"latissimus dorsi\"]', '[\"biceps\",\"rhomboids\",\"trapezius\"]', NULL, '[]', '[\"Hang from bar with overhand grip\",\"Pull chest to bar\",\"Lower slowly\",\"Repeat\"]', '2026-05-11 19:33:50', '[\"오버핸드 그립으로 철봉을 어깨너비보다 넓게 잡습니다.\",\"팔을 완전히 펴고 매달립니다.\",\"가슴을 철봉 쪽으로 당기며 몸을 올립니다.\",\"턱이 철봉 위로 올라오면 잠시 유지합니다.\",\"천천히 내려가며 반복합니다.\"]'),
(240011, 'Barbell Row', '바벨 로우', 'back', 'barbell', 'strength', 'intermediate', 'Compound rowing movement for back thickness.', '등 두께를 위한 복합 로잉 운동입니다.', '[\"rhomboids\",\"middle trapezius\"]', '[\"latissimus dorsi\",\"biceps\",\"rear deltoid\"]', NULL, '[]', '[\"Hinge at hips with bar\",\"Pull bar to lower chest\",\"Squeeze shoulder blades\",\"Lower with control\"]', '2026-05-11 19:33:50', '[\"발을 어깨너비로 벌리고 바벨을 잡습니다.\",\"엉덩이를 뒤로 빼며 상체를 약 45도로 숙입니다.\",\"바를 복부 쪽으로 당깁니다.\",\"날개뼈를 모으며 등 근육을 수축합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240012, 'Lat Pulldown', '랫 풀다운', 'back', 'cable', 'hypertrophy', 'beginner', 'Machine exercise targeting the latissimus dorsi.', '광배근을 타겟으로 하는 머신 운동입니다.', '[\"latissimus dorsi\"]', '[\"biceps\",\"rear deltoid\"]', NULL, '[]', '[\"Sit at pulldown machine\",\"Grip bar wider than shoulders\",\"Pull bar to upper chest\",\"Slowly return to start\"]', '2026-05-11 19:33:50', '[\"랫 풀다운 머신에 앉아 허벅지를 패드에 고정합니다.\",\"어깨너비보다 넓게 바를 잡습니다.\",\"바를 상부 가슴까지 당깁니다.\",\"광배근이 수축되는 것을 느낍니다.\",\"천천히 팔을 펴며 반복합니다.\"]'),
(240013, 'Seated Cable Row', '시티드 케이블 로우', 'back', 'cable', 'hypertrophy', 'beginner', 'Seated rowing exercise for back thickness.', '등 두께를 위한 앉아서 하는 로잉 운동입니다.', '[\"rhomboids\",\"middle trapezius\"]', '[\"biceps\",\"rear deltoid\"]', NULL, '[]', '[\"Sit at cable row machine\",\"Pull handle to abdomen\",\"Squeeze shoulder blades\",\"Extend arms slowly\"]', '2026-05-11 19:33:51', '[\"케이블 로우 머신에 앉아 발을 패드에 고정합니다.\",\"핸들을 잡고 상체를 약간 앞으로 기울입니다.\",\"핸들을 복부 쪽으로 당깁니다.\",\"날개뼈를 모으며 등 근육을 수축합니다.\",\"천천히 팔을 펴며 반복합니다.\"]'),
(240014, 'Dumbbell Row', '덤벨 로우', 'back', 'dumbbell', 'hypertrophy', 'beginner', 'Single arm rowing for back development.', '등 발달을 위한 단팔 로잉 운동입니다.', '[\"latissimus dorsi\",\"rhomboids\"]', '[\"biceps\",\"rear deltoid\"]', NULL, '[]', '[\"Place knee and hand on bench\",\"Row dumbbell to hip\",\"Squeeze lat at top\",\"Lower with control\"]', '2026-05-11 19:33:51', '[\"한쪽 무릎과 손을 벤치에 올려 지지합니다.\",\"반대 손으로 덤벨을 잡습니다.\",\"덤벨을 엉덩이 쪽으로 당깁니다.\",\"광배근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240015, 'T-Bar Row', 'T바 로우', 'back', 'barbell', 'strength', 'intermediate', 'Compound rowing using T-bar attachment.', 'T바 어태치먼트를 사용한 복합 로잉 운동입니다.', '[\"middle back\",\"rhomboids\"]', '[\"biceps\",\"lats\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row_with_Handle%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row_with_Handle%2F1.jpg\"]', '[\"Straddle bar with V-grip\",\"Hinge forward at hips\",\"Pull bar to chest\",\"Lower with control\"]', '2026-05-11 19:33:51', '[\"T바를 V자 핸들로 잡고 발을 어깨너비로 벌립니다.\",\"엉덩이를 뒤로 빼며 상체를 숙입니다.\",\"바를 가슴 쪽으로 당깁니다.\",\"날개뼈를 모으며 등 근육을 수축합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240016, 'Face Pull', '페이스 풀', 'back', 'cable', 'hypertrophy', 'beginner', 'Cable exercise for rear deltoids and rotator cuff.', '후면 삼각근과 회전근개를 위한 케이블 운동입니다.', '[\"rear deltoid\",\"rotator cuff\"]', '[\"trapezius\",\"rhomboids\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull%2F1.jpg\"]', '[\"Set cable at face height\",\"Pull rope to face\",\"Externally rotate at end\",\"Control return\"]', '2026-05-11 19:33:51', '[\"케이블을 얼굴 높이로 설정하고 로프를 잡습니다.\",\"로프를 얼굴 쪽으로 당깁니다.\",\"동작 끝에서 팔꿈치를 뒤로 당기며 외회전합니다.\",\"후면 삼각근과 회전근개가 수축되는 것을 느낍니다.\",\"천천히 원래 위치로 돌아가며 반복합니다.\"]'),
(240017, 'Overhead Press', '오버헤드 프레스', 'shoulders', 'barbell', 'strength', 'intermediate', 'Standing barbell press for shoulder strength.', '어깨 힘을 위한 서서 하는 바벨 프레스입니다.', '[\"anterior deltoid\",\"medial deltoid\"]', '[\"triceps\",\"upper trapezius\",\"core\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press%2F1.jpg\"]', '[\"Stand with bar at shoulders\",\"Press bar overhead\",\"Lock out arms at top\",\"Lower with control\"]', '2026-05-11 19:33:52', '[\"바벨을 어깨 앞에 위치시키고 어깨너비로 잡습니다.\",\"코어를 단단히 유지하며 바를 머리 위로 밀어 올립니다.\",\"팔꿈치를 완전히 펴며 정점에서 잠시 유지합니다.\",\"천천히 바를 어깨 위치로 내립니다.\",\"반복합니다.\"]'),
(240018, 'Dumbbell Shoulder Press', '덤벨 숄더 프레스', 'shoulders', 'dumbbell', 'hypertrophy', 'beginner', 'Seated or standing dumbbell press for shoulders.', '앉거나 서서 하는 덤벨 어깨 프레스입니다.', '[\"anterior deltoid\",\"medial deltoid\"]', '[\"triceps\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press%2F1.jpg\"]', '[\"Hold dumbbells at shoulder height\",\"Press overhead\",\"Squeeze at top\",\"Lower slowly\"]', '2026-05-11 19:33:52', '[\"양손에 덤벨을 들고 어깨 높이로 올립니다.\",\"덤벨을 머리 위로 밀어 올립니다.\",\"정점에서 어깨 근육을 수축합니다.\",\"천천히 어깨 높이로 내립니다.\",\"반복합니다.\"]'),
(240019, 'Lateral Raise', '레터럴 레이즈', 'shoulders', 'dumbbell', 'hypertrophy', 'beginner', 'Isolation exercise for medial deltoid.', '중간 삼각근을 고립시키는 운동입니다.', '[\"medial deltoid\"]', '[\"anterior deltoid\",\"trapezius\"]', NULL, '[]', '[\"Stand with dumbbells at sides\",\"Raise arms to shoulder height\",\"Slight bend in elbows\",\"Lower slowly\"]', '2026-05-11 19:33:52', '[\"양손에 덤벨을 들고 바르게 섭니다.\",\"팔꿈치를 약간 구부린 상태로 팔을 옆으로 올립니다.\",\"어깨 높이까지 올려 측면 삼각근을 수축합니다.\",\"천천히 내리며 반복합니다.\",\"반동을 사용하지 않도록 주의합니다.\"]'),
(240020, 'Front Raise', '프론트 레이즈', 'shoulders', 'dumbbell', 'hypertrophy', 'beginner', 'Targets the anterior deltoid.', '전면 삼각근을 타겟으로 합니다.', '[\"anterior deltoid\"]', '[\"medial deltoid\"]', NULL, '[]', '[\"Stand with dumbbells in front\",\"Raise one or both arms forward\",\"Stop at shoulder height\",\"Lower with control\"]', '2026-05-11 19:33:52', '[\"양손에 덤벨을 들고 바르게 섭니다.\",\"팔꿈치를 약간 구부린 상태로 팔을 앞으로 올립니다.\",\"어깨 높이까지 올려 전면 삼각근을 수축합니다.\",\"천천히 내리며 반복합니다.\",\"반동을 사용하지 않도록 주의합니다.\"]'),
(240021, 'Rear Delt Fly', '리어 델트 플라이', 'shoulders', 'dumbbell', 'hypertrophy', 'beginner', 'Targets the rear deltoid for balanced shoulder development.', '균형잡힌 어깨 발달을 위한 후면 삼각근 운동입니다.', '[\"rear deltoid\"]', '[\"rhomboids\",\"trapezius\"]', NULL, '[]', '[\"Bend forward at hips\",\"Raise arms out to sides\",\"Squeeze rear delts\",\"Lower slowly\"]', '2026-05-11 19:33:53', '[\"양손에 덤벨을 들고 상체를 앞으로 숙입니다.\",\"팔꿈치를 약간 구부린 상태로 팔을 옆으로 올립니다.\",\"후면 삼각근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"등이 둥글어지지 않도록 주의합니다.\"]'),
(240022, 'Arnold Press', '아놀드 프레스', 'shoulders', 'dumbbell', 'hypertrophy', 'intermediate', 'Rotating press invented by Arnold Schwarzenegger.', '아놀드 슈워제네거가 개발한 회전 프레스입니다.', '[\"anterior deltoid\",\"medial deltoid\"]', '[\"triceps\",\"rear deltoid\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press%2F1.jpg\"]', '[\"Start with palms facing you\",\"Rotate palms outward while pressing\",\"Press to full extension\",\"Reverse on the way down\"]', '2026-05-11 19:33:53', '[\"양손에 덤벨을 들고 손바닥이 몸 쪽을 향하도록 합니다.\",\"덤벨을 올리면서 손목을 회전시켜 손바닥이 앞을 향하게 합니다.\",\"머리 위로 완전히 밀어 올립니다.\",\"내리면서 반대로 손목을 회전시킵니다.\",\"반복합니다.\"]'),
(240023, 'Upright Row', '업라이트 로우', 'shoulders', 'barbell', 'hypertrophy', 'intermediate', 'Vertical pulling for shoulders and traps.', '어깨와 승모근을 위한 수직 당기기 운동입니다.', '[\"medial deltoid\",\"trapezius\"]', '[\"anterior deltoid\",\"biceps\"]', NULL, '[]', '[\"Hold bar with narrow grip\",\"Pull bar up along body\",\"Elbows lead the movement\",\"Lower with control\"]', '2026-05-11 19:33:53', '[\"바벨을 어깨너비보다 좁게 잡고 허벅지 앞에 위치시킵니다.\",\"팔꿈치를 높이 들며 바를 턱 아래까지 당깁니다.\",\"어깨와 승모근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"손목이 꺾이지 않도록 주의합니다.\"]'),
(240024, 'Barbell Curl', '바벨 컬', 'arms', 'barbell', 'hypertrophy', 'beginner', 'Classic bicep exercise with barbell.', '바벨을 이용한 클래식 이두 운동입니다.', '[\"biceps brachii\"]', '[\"brachialis\",\"brachioradialis\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl%2F1.jpg\"]', '[\"Stand with bar at thighs\",\"Curl bar to shoulders\",\"Squeeze biceps at top\",\"Lower slowly\"]', '2026-05-11 19:33:53', '[\"바벨을 어깨너비로 잡고 바르게 섭니다.\",\"팔꿈치를 몸에 붙인 채 바를 어깨 쪽으로 올립니다.\",\"이두근이 완전히 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"반동을 사용하지 않도록 주의합니다.\"]'),
(240025, 'Dumbbell Curl', '덤벨 컬', 'arms', 'dumbbell', 'hypertrophy', 'beginner', 'Alternating or simultaneous dumbbell curls.', '교대 또는 동시에 하는 덤벨 컬입니다.', '[\"biceps brachii\"]', '[\"brachialis\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Alternate_Bicep_Curl%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Alternate_Bicep_Curl%2F1.jpg\"]', '[\"Hold dumbbells at sides\",\"Curl one or both to shoulders\",\"Supinate wrist at top\",\"Lower with control\"]', '2026-05-11 19:33:53', '[\"양손에 덤벨을 들고 바르게 섭니다.\",\"한 팔씩 번갈아가며 덤벨을 어깨 쪽으로 올립니다.\",\"이두근이 완전히 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"반동을 사용하지 않도록 주의합니다.\"]'),
(240026, 'Hammer Curl', '해머 컬', 'arms', 'dumbbell', 'hypertrophy', 'beginner', 'Neutral grip curl targeting brachialis.', '상완근을 타겟으로 하는 중립 그립 컬입니다.', '[\"brachialis\",\"brachioradialis\"]', '[\"biceps brachii\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls%2F1.jpg\"]', '[\"Hold dumbbells with neutral grip\",\"Curl to shoulder height\",\"Keep wrist neutral\",\"Lower slowly\"]', '2026-05-11 19:33:54', '[\"양손에 덤벨을 들고 손바닥이 서로 마주보게 합니다.\",\"팔꿈치를 몸에 붙인 채 덤벨을 올립니다.\",\"상완근과 이두근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"반동을 사용하지 않도록 주의합니다.\"]'),
(240027, 'Tricep Pushdown', '트라이셉 푸시다운', 'arms', 'cable', 'hypertrophy', 'beginner', 'Cable exercise for tricep isolation.', '삼두근 고립을 위한 케이블 운동입니다.', '[\"triceps brachii\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown_-_Rope_Attachment%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown_-_Rope_Attachment%2F1.jpg\"]', '[\"Stand at cable machine\",\"Push bar down to thighs\",\"Squeeze triceps at bottom\",\"Control return\"]', '2026-05-11 19:33:54', '[\"케이블 머신에 로프를 연결하고 잡습니다.\",\"팔꿈치를 몸에 붙인 채 로프를 아래로 밀어 내립니다.\",\"삼두근이 완전히 수축되는 것을 느낍니다.\",\"천천히 올리며 반복합니다.\",\"팔꿈치가 움직이지 않도록 주의합니다.\"]'),
(240028, 'Skull Crushers', '스컬 크러셔', 'arms', 'barbell', 'hypertrophy', 'intermediate', 'Lying tricep extension for mass.', '삼두근 매스를 위한 누워서 하는 익스텐션입니다.', '[\"triceps brachii\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher%2F1.jpg\"]', '[\"Lie on bench with EZ bar\",\"Lower bar to forehead\",\"Extend arms to start\",\"Keep elbows tucked\"]', '2026-05-11 19:33:54', '[\"EZ바를 잡고 플랫 벤치에 눕습니다.\",\"팔꿈치를 고정한 채 바를 이마 쪽으로 내립니다.\",\"삼두근이 늘어나는 것을 느낍니다.\",\"삼두근을 수축하며 바를 올립니다.\",\"천천히 내리며 반복합니다.\"]'),
(240029, 'Tricep Dips', '트라이셉 딥스', 'arms', 'bodyweight', 'strength', 'beginner', 'Bodyweight tricep exercise using a bench.', '벤치를 이용한 맨몸 삼두근 운동입니다.', '[\"triceps brachii\"]', '[\"anterior deltoid\"]', NULL, '[]', '[\"Place hands on bench behind you\",\"Lower body down\",\"Push back up\",\"Keep elbows close\"]', '2026-05-11 19:33:54', '[\"평행봉을 양손으로 잡고 몸을 들어 올립니다.\",\"상체를 수직으로 유지합니다.\",\"팔꿈치가 90도가 될 때까지 내려갑니다.\",\"삼두근을 수축하며 다시 밀어 올립니다.\",\"천천히 내리며 반복합니다.\"]'),
(240030, 'Preacher Curl', '프리처 컬', 'arms', 'machine', 'hypertrophy', 'beginner', 'Isolated bicep curl on preacher bench.', '프리처 벤치에서 하는 고립 이두 컬입니다.', '[\"biceps brachii\"]', '[\"brachialis\"]', NULL, '[]', '[\"Rest arms on preacher bench\",\"Curl bar to chin\",\"Squeeze at top\",\"Lower fully to stretch\"]', '2026-05-11 19:33:55', '[\"프리처 컬 벤치에 앉아 팔을 패드에 올립니다.\",\"EZ바를 잡고 팔을 완전히 펍니다.\",\"이두근을 수축하며 바를 올립니다.\",\"정점에서 잠시 유지합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240031, 'Overhead Tricep Extension', '오버헤드 트라이셉 익스텐션', 'arms', 'dumbbell', 'hypertrophy', 'beginner', 'Overhead extension for long head of tricep.', '삼두근 장두를 위한 오버헤드 익스텐션입니다.', '[\"triceps brachii (long head)\"]', '[]', NULL, '[]', '[\"Hold dumbbell overhead\",\"Lower behind head\",\"Extend arms fully\",\"Keep elbows close\"]', '2026-05-11 19:33:55', '[\"덤벨을 양손으로 잡고 머리 위로 올립니다.\",\"팔꿈치를 고정한 채 덤벨을 머리 뒤로 내립니다.\",\"삼두근이 늘어나는 것을 느낍니다.\",\"삼두근을 수축하며 덤벨을 올립니다.\",\"천천히 내리며 반복합니다.\"]'),
(240032, 'Barbell Squat', '바벨 스쿼트', 'legs', 'barbell', 'strength', 'intermediate', 'The king of leg exercises for overall lower body strength.', '전체 하체 힘을 위한 하체 운동의 왕입니다.', '[\"quadriceps\",\"glutes\"]', '[\"hamstrings\",\"calves\",\"core\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Bar on upper back\",\"Feet shoulder width apart\",\"Squat to parallel or below\",\"Drive through heels to stand\"]', '2026-05-11 19:33:55', '[\"바벨을 상부 등에 올리고 발을 어깨너비로 벌립니다.\",\"가슴을 펴고 코어를 단단히 유지합니다.\",\"엉덩이를 뒤로 빼며 무릎이 발끝 방향으로 향하게 내려갑니다.\",\"허벅지가 바닥과 평행이 될 때까지 내려갑니다.\",\"발뒤꿈치로 바닥을 밀며 일어서서 반복합니다.\"]'),
(240033, 'Romanian Deadlift', '루마니안 데드리프트', 'legs', 'barbell', 'hypertrophy', 'intermediate', 'Hip hinge movement targeting hamstrings and glutes.', '햄스트링과 둔근을 타겟으로 하는 힙 힌지 운동입니다.', '[\"hamstrings\",\"glutes\"]', '[\"erector spinae\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift%2F1.jpg\"]', '[\"Hold bar at hips\",\"Hinge forward keeping bar close\",\"Feel hamstring stretch\",\"Drive hips forward to stand\"]', '2026-05-11 19:33:55', '[\"바벨을 어깨너비로 잡고 바르게 섭니다.\",\"무릎을 약간 구부린 채 엉덩이를 뒤로 빼며 상체를 숙입니다.\",\"등을 일직선으로 유지합니다.\",\"햄스트링이 충분히 늘어나면 멈춥니다.\",\"엉덩이를 앞으로 밀며 다시 서서 반복합니다.\"]'),
(240034, 'Leg Press', '레그 프레스', 'legs', 'machine', 'hypertrophy', 'beginner', 'Machine-based leg press for quad development.', '대퇴사두근 발달을 위한 머신 레그 프레스입니다.', '[\"quadriceps\"]', '[\"glutes\",\"hamstrings\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press%2F1.jpg\"]', '[\"Sit in leg press machine\",\"Place feet shoulder width on platform\",\"Lower platform to 90 degrees\",\"Press back to start\"]', '2026-05-11 19:33:56', '[\"레그 프레스 머신에 앉아 발을 플랫폼에 어깨너비로 놓습니다.\",\"안전 장치를 해제하고 무릎이 90도가 될 때까지 내립니다.\",\"발뒤꿈치로 플랫폼을 밀며 다리를 펍니다.\",\"무릎을 완전히 펴지 않도록 주의합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240035, 'Lunges', '런지', 'legs', 'bodyweight', 'endurance', 'beginner', 'Unilateral leg exercise for balance and strength.', '균형과 힘을 위한 단측 하체 운동입니다.', '[\"quadriceps\",\"glutes\"]', '[\"hamstrings\",\"calves\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Lunge%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Lunge%2F1.jpg\"]', '[\"Stand tall\",\"Step forward and lower knee\",\"Back knee near floor\",\"Push back to start\"]', '2026-05-11 19:33:56', '[\"바르게 서서 한 발을 앞으로 내딛습니다.\",\"뒷 무릎이 바닥에 닿을 때까지 내려갑니다.\",\"앞 무릎이 발끝을 넘지 않도록 합니다.\",\"앞발로 바닥을 밀며 원래 자세로 돌아옵니다.\",\"반대 발로 반복합니다.\"]'),
(240036, 'Leg Curl', '레그 컬', 'legs', 'machine', 'hypertrophy', 'beginner', 'Machine isolation for hamstrings.', '햄스트링 고립을 위한 머신 운동입니다.', '[\"hamstrings\"]', '[\"calves\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls%2F1.jpg\"]', '[\"Lie face down on machine\",\"Curl legs to glutes\",\"Squeeze hamstrings\",\"Lower slowly\"]', '2026-05-11 19:33:56', '[\"레그 컬 머신에 엎드려 발목을 패드에 고정합니다.\",\"햄스트링을 수축하며 발목을 엉덩이 쪽으로 올립니다.\",\"정점에서 잠시 유지합니다.\",\"천천히 내리며 반복합니다.\",\"허리가 들리지 않도록 주의합니다.\"]'),
(240037, 'Leg Extension', '레그 익스텐션', 'legs', 'machine', 'hypertrophy', 'beginner', 'Machine isolation for quadriceps.', '대퇴사두근 고립을 위한 머신 운동입니다.', '[\"quadriceps\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions%2F1.jpg\"]', '[\"Sit in leg extension machine\",\"Extend legs fully\",\"Squeeze quads at top\",\"Lower slowly\"]', '2026-05-11 19:33:56', '[\"레그 익스텐션 머신에 앉아 발목을 패드에 고정합니다.\",\"대퇴사두근을 수축하며 다리를 완전히 펍니다.\",\"정점에서 잠시 유지합니다.\",\"천천히 내리며 반복합니다.\",\"무릎 관절에 무리가 가지 않도록 주의합니다.\"]'),
(240038, 'Calf Raise', '카프 레이즈', 'legs', 'machine', 'hypertrophy', 'beginner', 'Isolation exercise for calf muscles.', '종아리 근육 고립 운동입니다.', '[\"gastrocnemius\",\"soleus\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises%2F1.jpg\"]', '[\"Stand on calf raise machine\",\"Rise up on toes\",\"Squeeze calves at top\",\"Lower heel below platform\"]', '2026-05-11 19:33:57', '[\"카프 레이즈 머신에 서서 어깨에 패드를 올립니다.\",\"발뒤꿈치를 최대한 올립니다.\",\"종아리 근육이 완전히 수축되는 것을 느낍니다.\",\"발뒤꿈치를 플랫폼 아래로 내립니다.\",\"충분히 늘어나면 반복합니다.\"]'),
(240039, 'Bulgarian Split Squat', '불가리안 스플릿 스쿼트', 'legs', 'dumbbell', 'hypertrophy', 'intermediate', 'Unilateral squat with rear foot elevated.', '뒷발을 올린 단측 스쿼트입니다.', '[\"quadriceps\",\"glutes\"]', '[\"hamstrings\",\"hip flexors\"]', NULL, '[]', '[\"Rear foot on bench\",\"Lower front leg to 90 degrees\",\"Keep torso upright\",\"Drive through front heel\"]', '2026-05-11 19:33:57', '[\"뒷발을 벤치에 올리고 앞발을 앞으로 내딛습니다.\",\"상체를 수직으로 유지하며 내려갑니다.\",\"앞 무릎이 90도가 될 때까지 내려갑니다.\",\"앞발로 바닥을 밀며 올라옵니다.\",\"목표 횟수만큼 반복 후 다리를 바꿉니다.\"]'),
(240040, 'Hack Squat', '핵 스쿼트', 'legs', 'machine', 'hypertrophy', 'intermediate', 'Machine squat emphasizing quadriceps.', '대퇴사두근을 강조하는 머신 스쿼트입니다.', '[\"quadriceps\"]', '[\"glutes\",\"hamstrings\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Position in hack squat machine\",\"Feet shoulder width on platform\",\"Lower to 90 degrees\",\"Press back up\"]', '2026-05-11 19:33:57', '[\"핵 스쿼트 머신에 등을 대고 어깨에 패드를 올립니다.\",\"발을 플랫폼에 어깨너비로 놓습니다.\",\"무릎이 90도가 될 때까지 내려갑니다.\",\"대퇴사두근을 수축하며 올라옵니다.\",\"천천히 내리며 반복합니다.\"]'),
(240041, 'Hip Thrust', '힙 스러스트', 'glutes', 'barbell', 'hypertrophy', 'intermediate', 'Best exercise for glute development.', '둔근 발달을 위한 최고의 운동입니다.', '[\"glutes\"]', '[\"hamstrings\",\"core\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust%2F1.jpg\"]', '[\"Sit against bench with bar on hips\",\"Drive hips up\",\"Squeeze glutes at top\",\"Lower with control\"]', '2026-05-11 19:33:57', '[\"벤치에 등 상부를 기대고 바벨을 골반에 올립니다.\",\"발을 바닥에 어깨너비로 놓습니다.\",\"엉덩이를 위로 밀어 올립니다.\",\"정점에서 둔근을 최대한 수축합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240042, 'Crunch', '크런치', 'abs', 'bodyweight', 'endurance', 'beginner', 'Basic abdominal crunch exercise.', '기본 복근 크런치 운동입니다.', '[\"rectus abdominis\"]', '[]', NULL, '[]', '[\"Lie on back with knees bent\",\"Hands behind head\",\"Curl shoulders off floor\",\"Lower slowly\"]', '2026-05-11 19:33:58', '[\"등을 대고 누워 무릎을 구부립니다.\",\"손을 머리 뒤에 가볍게 올립니다.\",\"복근을 수축하며 어깨를 바닥에서 들어 올립니다.\",\"복근이 완전히 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240043, 'Plank', '플랭크', 'abs', 'bodyweight', 'endurance', 'beginner', 'Isometric core stability exercise.', '등척성 코어 안정화 운동입니다.', '[\"core\",\"transverse abdominis\"]', '[\"glutes\",\"shoulders\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank%2F1.jpg\"]', '[\"Forearms on floor\",\"Body in straight line\",\"Hold position\",\"Breathe steadily\"]', '2026-05-11 19:33:58', '[\"전완을 바닥에 놓고 플랭크 자세를 취합니다.\",\"몸을 일직선으로 유지합니다.\",\"코어를 단단히 수축합니다.\",\"목표 시간만큼 자세를 유지합니다.\",\"엉덩이가 처지거나 올라가지 않도록 합니다.\"]'),
(240044, 'Leg Raise', '레그 레이즈', 'abs', 'bodyweight', 'endurance', 'intermediate', 'Lower ab exercise lying on back.', '누워서 하는 하복부 운동입니다.', '[\"lower rectus abdominis\"]', '[\"hip flexors\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Leg_Pull-In%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Leg_Pull-In%2F1.jpg\"]', '[\"Lie flat on back\",\"Keep legs straight\",\"Raise to 90 degrees\",\"Lower slowly without touching floor\"]', '2026-05-11 19:33:58', '[\"등을 대고 누워 다리를 펍니다.\",\"다리를 곧게 유지하며 90도까지 올립니다.\",\"하복근이 수축되는 것을 느낍니다.\",\"바닥에 닿지 않도록 천천히 내립니다.\",\"반복합니다.\"]'),
(240045, 'Russian Twist', '러시안 트위스트', 'abs', 'bodyweight', 'endurance', 'beginner', 'Rotational core exercise.', '회전 코어 운동입니다.', '[\"obliques\"]', '[\"rectus abdominis\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist%2F1.jpg\"]', '[\"Sit with knees bent\",\"Lean back slightly\",\"Rotate torso side to side\",\"Keep core engaged\"]', '2026-05-11 19:33:58', '[\"무릎을 구부리고 앉아 상체를 약간 뒤로 기울입니다.\",\"양손을 모아 몸통을 좌우로 회전합니다.\",\"복사근이 수축되는 것을 느낍니다.\",\"코어를 단단히 유지합니다.\",\"목표 횟수만큼 반복합니다.\"]'),
(240046, 'Cable Crunch', '케이블 크런치', 'abs', 'cable', 'hypertrophy', 'intermediate', 'Weighted crunch using cable for resistance.', '케이블 저항을 이용한 웨이티드 크런치입니다.', '[\"rectus abdominis\"]', '[\"obliques\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch%2F1.jpg\"]', '[\"Kneel at cable machine\",\"Hold rope at head\",\"Crunch down with core\",\"Return to start\"]', '2026-05-11 19:33:59', '[\"케이블 머신 앞에 무릎을 꿇습니다.\",\"로프를 머리 옆에 잡습니다.\",\"복근을 수축하며 아래로 구부립니다.\",\"복근이 완전히 수축되는 것을 느낍니다.\",\"천천히 원래 위치로 돌아가며 반복합니다.\"]'),
(240047, 'Hanging Leg Raise', '행잉 레그 레이즈', 'abs', 'bodyweight', 'strength', 'advanced', 'Advanced core exercise hanging from bar.', '바에 매달려 하는 고급 코어 운동입니다.', '[\"lower rectus abdominis\",\"hip flexors\"]', '[\"obliques\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise%2F1.jpg\"]', '[\"Hang from pull-up bar\",\"Raise legs to 90 degrees\",\"Control the movement\",\"Lower slowly\"]', '2026-05-11 19:33:59', '[\"철봉에 매달립니다.\",\"다리를 곧게 유지하며 90도까지 올립니다.\",\"하복근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"반동을 사용하지 않도록 주의합니다.\"]'),
(240048, 'Ab Wheel Rollout', 'AB 휠 롤아웃', 'abs', 'none', 'strength', 'advanced', 'Full core exercise using ab wheel.', 'AB 휠을 이용한 전체 코어 운동입니다.', '[\"core\",\"rectus abdominis\"]', '[\"lats\",\"shoulders\"]', NULL, '[]', '[\"Kneel with ab wheel\",\"Roll forward until extended\",\"Pull back using core\",\"Keep hips low\"]', '2026-05-11 19:33:59', '[\"무릎을 꿇고 AB 휠을 잡습니다.\",\"코어를 단단히 유지하며 앞으로 굴립니다.\",\"몸이 완전히 펴질 때까지 굴립니다.\",\"코어를 수축하며 다시 당겨옵니다.\",\"허리가 처지지 않도록 주의합니다.\"]'),
(240049, 'Side Plank', '사이드 플랭크', 'abs', 'bodyweight', 'endurance', 'beginner', 'Lateral core stability exercise.', '측면 코어 안정화 운동입니다.', '[\"obliques\"]', '[\"core\",\"hip abductors\"]', NULL, '[]', '[\"Lie on side\",\"Support on forearm and feet\",\"Keep body straight\",\"Hold position\"]', '2026-05-11 19:33:59', '[\"옆으로 누워 전완을 바닥에 놓습니다.\",\"엉덩이를 들어 올려 몸을 일직선으로 만듭니다.\",\"복사근을 수축합니다.\",\"목표 시간만큼 자세를 유지합니다.\",\"반대쪽으로 반복합니다.\"]'),
(240050, 'Treadmill Run', '트레드밀 달리기', 'cardio', 'machine', 'cardio', 'beginner', 'Running on treadmill for cardiovascular fitness.', '심폐 체력을 위한 트레드밀 달리기입니다.', '[\"quadriceps\",\"hamstrings\",\"calves\"]', '[\"glutes\",\"core\"]', NULL, '[]', '[\"Set desired speed\",\"Start with warm-up walk\",\"Increase to running pace\",\"Cool down at end\"]', '2026-05-11 19:34:00', '[\"원하는 속도를 설정합니다.\",\"워밍업 걷기로 시작합니다.\",\"달리기 속도로 증가합니다.\",\"목표 시간 또는 거리를 달립니다.\",\"쿨다운 걷기로 마무리합니다.\"]'),
(240051, 'Jump Rope', '줄넘기', 'cardio', 'none', 'cardio', 'beginner', 'Classic cardio exercise with jump rope.', '줄넘기를 이용한 클래식 유산소 운동입니다.', '[\"calves\",\"shoulders\"]', '[\"core\",\"forearms\"]', NULL, '[]', '[\"Hold rope handles\",\"Jump with both feet\",\"Keep rhythm consistent\",\"Land softly on balls of feet\"]', '2026-05-11 19:34:00', '[\"줄넘기 손잡이를 양손에 잡습니다.\",\"양발로 함께 점프합니다.\",\"일정한 리듬을 유지합니다.\",\"발볼로 부드럽게 착지합니다.\",\"목표 횟수 또는 시간만큼 반복합니다.\"]'),
(240052, 'Burpee', '버피', 'cardio', 'bodyweight', 'cardio', 'intermediate', 'Full body cardio exercise.', '전신 유산소 운동입니다.', '[\"full body\"]', '[]', NULL, '[]', '[\"Start standing\",\"Drop to push-up position\",\"Do a push-up\",\"Jump feet to hands and jump up\"]', '2026-05-11 19:34:00', '[\"바르게 서서 시작합니다.\",\"손을 바닥에 짚으며 발을 뒤로 뻗어 푸시업 자세를 만듭니다.\",\"푸시업을 한 번 합니다.\",\"발을 손 쪽으로 당기며 점프합니다.\",\"손을 위로 올리며 점프하고 반복합니다.\"]'),
(240053, 'Rowing Machine', '로잉 머신', 'cardio', 'machine', 'cardio', 'beginner', 'Full body cardio on rowing machine.', '로잉 머신을 이용한 전신 유산소 운동입니다.', '[\"back\",\"legs\",\"arms\"]', '[\"core\"]', NULL, '[]', '[\"Sit on rowing machine\",\"Push with legs first\",\"Pull handle to chest\",\"Return to start position\"]', '2026-05-11 19:34:00', '[\"로잉 머신에 앉아 발을 고정합니다.\",\"핸들을 잡고 다리를 먼저 밀어냅니다.\",\"다리가 펴지면 핸들을 가슴 쪽으로 당깁니다.\",\"팔을 펴며 상체를 앞으로 기울입니다.\",\"다리를 구부리며 원래 자세로 돌아가 반복합니다.\"]'),
(240054, 'Stationary Bike', '고정식 자전거', 'cardio', 'machine', 'cardio', 'beginner', 'Low-impact cardio on stationary bike.', '고정식 자전거를 이용한 저충격 유산소 운동입니다.', '[\"quadriceps\",\"hamstrings\"]', '[\"calves\",\"glutes\"]', NULL, '[]', '[\"Adjust seat height\",\"Start pedaling at comfortable pace\",\"Maintain steady cadence\",\"Increase resistance as needed\"]', '2026-05-11 19:34:00', '[\"안장 높이를 조절합니다.\",\"편안한 속도로 페달링을 시작합니다.\",\"일정한 케이던스를 유지합니다.\",\"필요에 따라 저항을 높입니다.\",\"목표 시간만큼 유지합니다.\"]'),
(240055, 'Mountain Climbers', '마운틴 클라이머', 'cardio', 'bodyweight', 'cardio', 'beginner', 'Dynamic plank exercise for cardio and core.', '유산소와 코어를 위한 동적 플랭크 운동입니다.', '[\"core\",\"hip flexors\"]', '[\"shoulders\",\"legs\"]', NULL, '[]', '[\"Start in plank position\",\"Drive knee to chest alternately\",\"Keep hips level\",\"Maintain quick pace\"]', '2026-05-11 19:34:01', '[\"플랭크 자세를 취합니다.\",\"한쪽 무릎을 가슴 쪽으로 당깁니다.\",\"빠르게 다리를 교체합니다.\",\"코어를 단단히 유지합니다.\",\"목표 횟수 또는 시간만큼 반복합니다.\"]'),
(240056, 'Chest Stretch', '가슴 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Doorway or wall stretch for chest and shoulders.', '문이나 벽을 이용한 가슴과 어깨 스트레칭입니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Stand in doorway\",\"Place forearms on frame\",\"Lean forward gently\",\"Hold 30 seconds\"]', '2026-05-11 19:34:01', '[\"바르게 서거나 앉습니다.\",\"양팔을 뒤로 모아 손을 깍지 낍니다.\",\"가슴을 앞으로 내밀며 어깨를 뒤로 당깁니다.\",\"가슴 근육이 늘어나는 것을 느낍니다.\",\"30초간 유지합니다.\"]'),
(240057, 'Hip Flexor Stretch', '고관절 굴곡근 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Kneeling stretch for hip flexors.', '무릎 꿇고 하는 고관절 굴곡근 스트레칭입니다.', '[\"hip flexors\",\"iliopsoas\"]', '[\"quadriceps\"]', NULL, '[]', '[\"Kneel on one knee\",\"Push hips forward\",\"Feel stretch in front of hip\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:01', '[\"한쪽 무릎을 바닥에 꿇습니다.\",\"앞발을 앞으로 내딛어 런지 자세를 만듭니다.\",\"엉덩이를 앞으로 밀며 고관절 굴곡근을 늘입니다.\",\"상체를 수직으로 유지합니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240058, 'Hamstring Stretch', '햄스트링 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Seated or standing hamstring stretch.', '앉거나 서서 하는 햄스트링 스트레칭입니다.', '[\"hamstrings\"]', '[\"lower back\"]', NULL, '[]', '[\"Sit with legs extended\",\"Reach toward toes\",\"Keep back straight\",\"Hold 30 seconds\"]', '2026-05-11 19:34:01', '[\"바닥에 앉아 다리를 앞으로 펍니다.\",\"엉덩이를 뒤로 빼며 상체를 앞으로 숙입니다.\",\"손이 발 쪽으로 향하도록 합니다.\",\"햄스트링이 늘어나는 것을 느낍니다.\",\"30~60초간 유지합니다.\"]'),
(240059, 'Shoulder Cross Stretch', '어깨 크로스 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Cross-body shoulder stretch.', '몸을 가로질러 하는 어깨 스트레칭입니다.', '[\"posterior deltoid\",\"rotator cuff\"]', '[\"rhomboids\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Bring arm across chest\",\"Hold with other arm\",\"Feel stretch in shoulder\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:02', '[\"한쪽 팔을 가슴 앞으로 뻗습니다.\",\"반대 팔로 뻗은 팔의 팔꿈치를 잡아당깁니다.\",\"후면 삼각근이 늘어나는 것을 느낍니다.\",\"30초간 유지합니다.\",\"반대쪽으로 반복합니다.\"]'),
(240060, 'Cat-Cow Stretch', '캣-카우 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Spinal mobility exercise on all fours.', '네발 기기 자세로 하는 척추 가동성 운동입니다.', '[\"spine\",\"core\"]', '[\"neck\",\"hips\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Start on hands and knees\",\"Arch back up (cat)\",\"Drop belly down (cow)\",\"Flow between positions\"]', '2026-05-11 19:34:02', '[\"네발 기기 자세를 취합니다.\",\"숨을 내쉬며 등을 위로 둥글게 만듭니다 (캣 자세).\",\"숨을 들이쉬며 등을 아래로 내립니다 (카우 자세).\",\"천천히 반복합니다.\",\"척추 전체가 움직이는 것을 느낍니다.\"]'),
(240061, 'Pigeon Pose', '비둘기 자세', 'stretching', 'none', 'flexibility', 'intermediate', 'Deep hip opener from yoga.', '요가에서 유래한 깊은 고관절 스트레칭입니다.', '[\"glutes\",\"hip external rotators\"]', '[\"hip flexors\"]', NULL, '[]', '[\"Bring one leg forward bent\",\"Extend other leg back\",\"Lower torso forward\",\"Hold 60 seconds each side\"]', '2026-05-11 19:34:02', '[\"한쪽 다리를 앞으로 구부려 바닥에 놓습니다.\",\"뒷다리를 뒤로 뻗습니다.\",\"상체를 앞으로 숙입니다.\",\"둔근이 늘어나는 것을 느낍니다.\",\"30~60초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240062, 'Child\'s Pose', '아이 자세', 'stretching', 'none', 'flexibility', 'beginner', 'Resting yoga pose for back and hips.', '등과 고관절을 위한 휴식 요가 자세입니다.', '[\"lower back\",\"hips\"]', '[\"shoulders\",\"ankles\"]', NULL, '[]', '[\"Kneel and sit back on heels\",\"Extend arms forward\",\"Rest forehead on floor\",\"Breathe deeply\"]', '2026-05-11 19:34:02', '[\"무릎을 꿇고 앉습니다.\",\"상체를 앞으로 숙이며 팔을 앞으로 뻗습니다.\",\"이마를 바닥에 내립니다.\",\"허리와 등이 늘어나는 것을 느낍니다.\",\"30~60초간 유지합니다.\"]'),
(240063, 'Thoracic Rotation', '흉추 회전 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Upper back rotation for mobility.', '가동성을 위한 상부 등 회전 운동입니다.', '[\"thoracic spine\"]', '[\"obliques\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Sit or kneel\",\"Place hand behind head\",\"Rotate upper body\",\"Hold at end range\"]', '2026-05-11 19:34:03', '[\"네발 기기 자세를 취합니다.\",\"한 손을 머리 뒤에 올립니다.\",\"팔꿈치를 위로 향하며 상체를 회전합니다.\",\"흉추가 회전되는 것을 느낍니다.\",\"반대쪽으로 반복합니다.\"]'),
(240064, 'Calf Stretch', '종아리 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Wall calf stretch for flexibility.', '유연성을 위한 벽 종아리 스트레칭입니다.', '[\"gastrocnemius\",\"soleus\"]', '[]', NULL, '[]', '[\"Stand facing wall\",\"Place hands on wall\",\"Step one foot back\",\"Press heel into floor\"]', '2026-05-11 19:34:03', '[\"벽 앞에 서서 한 발을 뒤로 뻗습니다.\",\"뒷발 뒤꿈치를 바닥에 붙입니다.\",\"앞으로 기울이며 종아리를 늘입니다.\",\"종아리 근육이 늘어나는 것을 느낍니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240065, 'Tricep Stretch', '삼두근 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Overhead tricep stretch.', '오버헤드 삼두근 스트레칭입니다.', '[\"triceps brachii\"]', '[\"shoulder\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Raise arm overhead\",\"Bend elbow behind head\",\"Push elbow with other hand\",\"Hold 30 seconds\"]', '2026-05-11 19:34:03', '[\"한 팔을 머리 위로 올립니다.\",\"팔꿈치를 구부려 손이 등 위쪽에 닿도록 합니다.\",\"반대 손으로 팔꿈치를 잡아당깁니다.\",\"삼두근이 늘어나는 것을 느낍니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240066, 'Quad Stretch', '대퇴사두근 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Standing quad stretch.', '서서 하는 대퇴사두근 스트레칭입니다.', '[\"quadriceps\"]', '[\"hip flexors\"]', NULL, '[]', '[\"Stand on one leg\",\"Pull other foot to glute\",\"Keep knees together\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:03', '[\"바르게 서서 한 발을 뒤로 들어 올립니다.\",\"같은 쪽 손으로 발목을 잡습니다.\",\"무릎을 모으며 대퇴사두근을 늘입니다.\",\"균형을 유지합니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240067, 'Glute Stretch', '둔근 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Figure-4 glute stretch.', '숫자 4 모양의 둔근 스트레칭입니다.', '[\"glutes\"]', '[\"hip external rotators\"]', NULL, '[]', '[\"Lie on back\",\"Cross ankle over opposite knee\",\"Pull legs toward chest\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:04', '[\"등을 대고 누워 한쪽 무릎을 구부립니다.\",\"구부린 다리를 반대쪽으로 넘깁니다.\",\"둔근이 늘어나는 것을 느낍니다.\",\"30초간 유지합니다.\",\"반대쪽으로 반복합니다.\"]'),
(240068, 'Clean and Press', '클린 앤 프레스', 'full_body', 'barbell', 'strength', 'advanced', 'Olympic-style full body power movement.', '올림픽 스타일의 전신 파워 운동입니다.', '[\"full body\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Pull bar from floor\",\"Catch at shoulders\",\"Press overhead\",\"Lower with control\"]', '2026-05-11 19:34:04', '[\"바벨을 어깨너비로 잡고 바르게 섭니다.\",\"바를 어깨 높이로 빠르게 당겨 올립니다 (클린).\",\"바를 머리 위로 밀어 올립니다 (프레스).\",\"천천히 바를 어깨로 내립니다.\",\"바를 바닥으로 내리며 반복합니다.\"]'),
(240069, 'Kettlebell Swing', '케틀벨 스윙', 'full_body', 'kettlebell', 'cardio', 'intermediate', 'Dynamic hip hinge with kettlebell.', '케틀벨을 이용한 동적 힙 힌지 운동입니다.', '[\"glutes\",\"hamstrings\"]', '[\"core\",\"shoulders\",\"back\"]', NULL, '[]', '[\"Hinge at hips with kettlebell\",\"Swing bell between legs\",\"Drive hips forward\",\"Let bell float to shoulder height\"]', '2026-05-11 19:34:04', '[\"발을 어깨너비로 벌리고 케틀벨을 잡습니다.\",\"엉덩이를 뒤로 빼며 케틀벨을 다리 사이로 내립니다.\",\"엉덩이를 앞으로 밀며 케틀벨을 어깨 높이로 올립니다.\",\"코어를 단단히 유지합니다.\",\"리듬감 있게 반복합니다.\"]'),
(240070, 'Turkish Get-Up', '터키시 겟업', 'full_body', 'kettlebell', 'strength', 'advanced', 'Complex full body movement with kettlebell.', '케틀벨을 이용한 복합 전신 운동입니다.', '[\"full body\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Lie with KB pressed up\",\"Roll to elbow then hand\",\"Sweep leg through\",\"Stand up fully\"]', '2026-05-11 19:34:04', '[\"등을 대고 누워 한 손으로 케틀벨을 들어 올립니다.\",\"반대 팔과 다리로 지지하며 일어납니다.\",\"완전히 서서 케틀벨을 위로 유지합니다.\",\"역순으로 다시 눕습니다.\",\"반대쪽으로 반복합니다.\"]'),
(240071, 'Thruster', '스러스터', 'full_body', 'barbell', 'cardio', 'advanced', 'Front squat to overhead press combination.', '프론트 스쿼트와 오버헤드 프레스 조합 운동입니다.', '[\"quadriceps\",\"shoulders\"]', '[\"glutes\",\"triceps\",\"core\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Hold bar at shoulders\",\"Squat to parallel\",\"Drive up and press overhead\",\"Lower bar to shoulders\"]', '2026-05-11 19:34:05', '[\"바벨을 어깨에 올리고 스쿼트 자세를 취합니다.\",\"스쿼트를 내려갑니다.\",\"올라오는 힘을 이용해 바를 머리 위로 밀어 올립니다.\",\"바를 어깨로 내리며 반복합니다.\",\"전신을 연속적으로 사용합니다.\"]'),
(240072, 'Pec Deck Machine', '펙 덱 머신', 'chest', 'machine', 'hypertrophy', 'beginner', 'Machine fly for chest isolation.', '가슴 고립을 위한 머신 플라이입니다.', '[\"pectoralis major\"]', '[\"anterior deltoid\"]', NULL, '[]', '[\"Sit in pec deck machine\",\"Bring arms together in front\",\"Squeeze chest\",\"Open arms slowly\"]', '2026-05-11 19:34:05', '[\"펙 덱 머신에 앉아 등을 패드에 밀착합니다.\",\"양팔을 패드에 올리고 팔꿈치를 90도로 구부립니다.\",\"가슴 근육을 수축하며 팔을 앞으로 모읍니다.\",\"정점에서 1초간 유지합니다.\",\"천천히 원래 위치로 돌아가며 반복합니다.\"]'),
(240073, 'Incline Dumbbell Fly', '인클라인 덤벨 플라이', 'chest', 'dumbbell', 'hypertrophy', 'intermediate', 'Upper chest fly on incline bench.', '인클라인 벤치에서 하는 상부 가슴 플라이입니다.', '[\"upper pectoralis major\"]', '[\"anterior deltoid\"]', NULL, '[]', '[\"Set bench to 30-45 degrees\",\"Hold dumbbells above chest\",\"Lower in wide arc\",\"Bring back together\"]', '2026-05-11 19:34:05', '[\"벤치를 30~45도로 기울이고 덤벨을 들고 눕습니다.\",\"팔꿈치를 약간 구부린 상태로 팔을 옆으로 넓게 벌립니다.\",\"상부 가슴이 충분히 늘어나는 것을 느낍니다.\",\"상부 가슴을 수축하며 팔을 다시 모읍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240074, 'Chin-Up', '친업', 'back', 'bodyweight', 'strength', 'intermediate', 'Underhand grip pull-up targeting biceps and lats.', '이두근과 광배근을 타겟으로 하는 언더핸드 풀업입니다.', '[\"latissimus dorsi\",\"biceps\"]', '[\"rhomboids\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up%2F1.jpg\"]', '[\"Hang with underhand grip\",\"Pull chin above bar\",\"Lower slowly\",\"Full extension at bottom\"]', '2026-05-11 19:34:05', '[\"언더핸드 그립으로 철봉을 어깨너비로 잡습니다.\",\"팔을 완전히 펴고 매달립니다.\",\"가슴을 철봉 쪽으로 당기며 몸을 올립니다.\",\"턱이 철봉 위로 올라오면 잠시 유지합니다.\",\"천천히 내려가며 반복합니다.\"]'),
(240075, 'Good Morning', '굿모닝', 'back', 'barbell', 'strength', 'intermediate', 'Hip hinge for lower back and hamstrings.', '허리와 햄스트링을 위한 힙 힌지 운동입니다.', '[\"erector spinae\",\"hamstrings\"]', '[\"glutes\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning%2F1.jpg\"]', '[\"Bar on upper back\",\"Hinge forward at hips\",\"Keep back straight\",\"Return to upright\"]', '2026-05-11 19:34:06', '[\"바벨을 상부 등에 올리고 발을 어깨너비로 벌립니다.\",\"무릎을 약간 구부린 상태로 엉덩이를 뒤로 빼며 상체를 숙입니다.\",\"등을 일직선으로 유지합니다.\",\"햄스트링이 충분히 늘어나면 멈춥니다.\",\"엉덩이를 앞으로 밀며 다시 서서 반복합니다.\"]'),
(240076, 'Rack Pull', '랙 풀', 'back', 'barbell', 'strength', 'intermediate', 'Partial deadlift from rack for upper back.', '상부 등을 위한 랙에서 하는 부분 데드리프트입니다.', '[\"trapezius\",\"erector spinae\"]', '[\"rhomboids\",\"lats\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift%2F1.jpg\"]', '[\"Set bar at knee height in rack\",\"Deadlift from this position\",\"Focus on upper back\",\"Lower with control\"]', '2026-05-11 19:34:06', '[\"랙에서 바를 무릎 높이로 설정합니다.\",\"데드리프트 자세로 바를 잡습니다.\",\"코어와 상부 등을 단단히 유지하며 바를 들어 올립니다.\",\"엉덩이를 완전히 펴며 동작을 마무리합니다.\",\"천천히 바를 내리며 반복합니다.\"]'),
(240077, 'Cable Lateral Raise', '케이블 레터럴 레이즈', 'shoulders', 'cable', 'hypertrophy', 'beginner', 'Cable version of lateral raise for constant tension.', '지속적인 장력을 위한 케이블 레터럴 레이즈입니다.', '[\"medial deltoid\"]', '[\"anterior deltoid\"]', NULL, '[]', '[\"Stand beside cable\",\"Pull cable up to shoulder height\",\"Keep slight bend in elbow\",\"Lower slowly\"]', '2026-05-11 19:34:06', '[\"케이블 머신 옆에 서서 케이블을 잡습니다.\",\"팔꿈치를 약간 구부린 상태로 팔을 옆으로 올립니다.\",\"어깨 높이까지 올려 측면 삼각근을 수축합니다.\",\"천천히 내리며 반복합니다.\",\"케이블이 지속적인 장력을 제공합니다.\"]'),
(240078, 'Shrug', '슈러그', 'shoulders', 'barbell', 'hypertrophy', 'beginner', 'Trapezius exercise for upper back thickness.', '상부 등 두께를 위한 승모근 운동입니다.', '[\"upper trapezius\"]', '[\"levator scapulae\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug%2F1.jpg\"]', '[\"Hold bar at thighs\",\"Elevate shoulders to ears\",\"Hold briefly at top\",\"Lower slowly\"]', '2026-05-11 19:34:06', '[\"바벨을 어깨너비로 잡고 허벅지 앞에 위치시킵니다.\",\"어깨를 귀 쪽으로 최대한 올립니다.\",\"정점에서 1~2초 유지합니다.\",\"천천히 어깨를 내립니다.\",\"반복합니다.\"]'),
(240079, 'Sumo Deadlift', '스모 데드리프트', 'legs', 'barbell', 'strength', 'intermediate', 'Wide stance deadlift targeting inner thighs and glutes.', '내전근과 둔근을 타겟으로 하는 넓은 스탠스 데드리프트입니다.', '[\"glutes\",\"inner thighs\"]', '[\"hamstrings\",\"quadriceps\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift%2F1.jpg\"]', '[\"Wide stance with toes out\",\"Grip bar inside legs\",\"Push floor away\",\"Lock out hips at top\"]', '2026-05-11 19:34:07', '[\"발을 어깨너비보다 넓게 벌리고 발끝을 바깥으로 향합니다.\",\"바를 다리 안쪽으로 잡습니다.\",\"코어를 단단히 유지하며 바를 들어 올립니다.\",\"엉덩이를 앞으로 밀며 완전히 서서 동작을 마무리합니다.\",\"천천히 바를 내리며 반복합니다.\"]'),
(240080, 'Step Up', '스텝업', 'legs', 'dumbbell', 'endurance', 'beginner', 'Unilateral step exercise for legs.', '하체를 위한 단측 스텝 운동입니다.', '[\"quadriceps\",\"glutes\"]', '[\"hamstrings\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Stand before box or bench\",\"Step up with one foot\",\"Bring other foot up\",\"Step back down\"]', '2026-05-11 19:34:07', '[\"박스나 벤치 앞에 서서 덤벨을 양손에 듭니다.\",\"한 발을 박스 위에 올립니다.\",\"앞발로 바닥을 밀며 올라옵니다.\",\"다른 발을 박스 위로 올립니다.\",\"천천히 내려와 반복합니다.\"]'),
(240081, 'Wall Sit', '월 싯', 'legs', 'bodyweight', 'endurance', 'beginner', 'Isometric quad exercise against wall.', '벽에 기대어 하는 등척성 대퇴사두근 운동입니다.', '[\"quadriceps\"]', '[\"glutes\",\"calves\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat%2F1.jpg\"]', '[\"Back against wall\",\"Slide down to 90 degrees\",\"Hold position\",\"Keep knees over ankles\"]', '2026-05-11 19:34:07', '[\"벽에 등을 대고 섭니다.\",\"무릎이 90도가 될 때까지 미끄러져 내려갑니다.\",\"허벅지가 바닥과 평행이 되도록 합니다.\",\"이 자세를 목표 시간만큼 유지합니다.\",\"무릎이 발끝 위에 오도록 합니다.\"]'),
(240082, 'Glute Bridge', '글루트 브릿지', 'glutes', 'bodyweight', 'hypertrophy', 'beginner', 'Floor exercise for glute activation.', '둔근 활성화를 위한 바닥 운동입니다.', '[\"glutes\"]', '[\"hamstrings\",\"core\"]', NULL, '[]', '[\"Lie on back with knees bent\",\"Drive hips up\",\"Squeeze glutes at top\",\"Lower slowly\"]', '2026-05-11 19:34:07', '[\"등을 대고 누워 무릎을 구부리고 발을 바닥에 놓습니다.\",\"엉덩이를 위로 밀어 올립니다.\",\"정점에서 둔근을 최대한 수축합니다.\",\"천천히 내리며 반복합니다.\",\"허리가 과도하게 아치되지 않도록 합니다.\"]'),
(240083, 'Box Jump', '박스 점프', 'legs', 'bodyweight', 'cardio', 'intermediate', 'Plyometric jump for explosive power.', '폭발적인 파워를 위한 플라이오메트릭 점프입니다.', '[\"quadriceps\",\"glutes\"]', '[\"hamstrings\",\"calves\"]', NULL, '[]', '[\"Stand before box\",\"Squat slightly\",\"Jump onto box\",\"Step down carefully\"]', '2026-05-11 19:34:07', '[\"박스 앞에 어깨너비로 서서 무릎을 약간 구부립니다.\",\"팔을 뒤로 당겼다가 앞으로 흔들며 박스 위로 점프합니다.\",\"부드럽게 착지하며 무릎을 구부려 충격을 흡수합니다.\",\"박스에서 조심스럽게 내려옵니다.\",\"반복합니다.\"]'),
(240084, 'Cable Curl', '케이블 컬', 'arms', 'cable', 'hypertrophy', 'beginner', 'Bicep curl with cable for constant tension.', '지속적인 장력을 위한 케이블 이두 컬입니다.', '[\"biceps brachii\"]', '[\"brachialis\"]', NULL, '[]', '[\"Stand at cable machine\",\"Curl handle to shoulder\",\"Squeeze bicep at top\",\"Lower slowly\"]', '2026-05-11 19:34:08', '[\"케이블 머신 앞에 서서 바를 잡습니다.\",\"팔꿈치를 몸에 붙인 채 바를 어깨 쪽으로 올립니다.\",\"이두근이 완전히 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"케이블이 지속적인 장력을 제공합니다.\"]'),
(240085, 'Concentration Curl', '컨센트레이션 컬', 'arms', 'dumbbell', 'hypertrophy', 'beginner', 'Seated isolation curl for bicep peak.', '이두근 피크를 위한 앉아서 하는 고립 컬입니다.', '[\"biceps brachii\"]', '[]', NULL, '[]', '[\"Sit with elbow on inner thigh\",\"Curl dumbbell to shoulder\",\"Squeeze at top\",\"Lower fully\"]', '2026-05-11 19:34:08', '[\"벤치에 앉아 팔꿈치를 허벅지 안쪽에 고정합니다.\",\"덤벨을 잡고 팔을 완전히 펍니다.\",\"이두근을 수축하며 덤벨을 올립니다.\",\"정점에서 잠시 유지합니다.\",\"천천히 내리며 반복합니다.\"]'),
(240086, 'Close Grip Bench Press', '클로즈 그립 벤치프레스', 'arms', 'barbell', 'strength', 'intermediate', 'Narrow grip bench press for tricep mass.', '삼두근 매스를 위한 좁은 그립 벤치프레스입니다.', '[\"triceps brachii\"]', '[\"pectoralis major\",\"anterior deltoid\"]', NULL, '[]', '[\"Grip bar shoulder width\",\"Lower to lower chest\",\"Keep elbows close\",\"Press up explosively\"]', '2026-05-11 19:34:08', '[\"플랫 벤치에 눕고 바를 어깨너비로 좁게 잡습니다.\",\"팔꿈치를 몸에 붙인 채 바를 하부 가슴까지 내립니다.\",\"삼두근을 수축하며 바를 밀어 올립니다.\",\"천천히 내리며 반복합니다.\",\"손목이 꺾이지 않도록 주의합니다.\"]'),
(240087, 'Wrist Curl', '손목 컬', 'arms', 'barbell', 'endurance', 'beginner', 'Forearm exercise for wrist flexors.', '손목 굴곡근을 위한 전완근 운동입니다.', '[\"wrist flexors\",\"forearms\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl%2F1.jpg\"]', '[\"Rest forearms on bench\",\"Hold bar with underhand grip\",\"Curl wrists up\",\"Lower fully\"]', '2026-05-11 19:34:08', '[\"벤치에 앉아 전완을 벤치 위에 올립니다.\",\"바벨을 언더핸드 그립으로 잡습니다.\",\"손목을 위로 올립니다.\",\"전완 굴곡근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240088, 'Bicycle Crunch', '바이시클 크런치', 'abs', 'bodyweight', 'endurance', 'beginner', 'Rotational crunch for obliques.', '복사근을 위한 회전 크런치입니다.', '[\"obliques\",\"rectus abdominis\"]', '[\"hip flexors\"]', NULL, '[]', '[\"Lie on back\",\"Bring opposite elbow to knee\",\"Alternate sides\",\"Keep lower back pressed down\"]', '2026-05-11 19:34:09', '[\"등을 대고 누워 손을 머리 뒤에 놓습니다.\",\"한쪽 무릎을 당기며 반대쪽 팔꿈치를 무릎 쪽으로 가져갑니다.\",\"좌우를 번갈아가며 반복합니다.\",\"복사근이 수축되는 것을 느낍니다.\",\"허리가 바닥에서 들리지 않도록 합니다.\"]'),
(240089, 'V-Up', 'V업', 'abs', 'bodyweight', 'strength', 'intermediate', 'Full body crunch targeting entire core.', '전체 코어를 타겟으로 하는 전신 크런치입니다.', '[\"rectus abdominis\",\"hip flexors\"]', '[\"obliques\"]', NULL, '[]', '[\"Lie flat on back\",\"Simultaneously raise legs and torso\",\"Touch toes at top\",\"Lower with control\"]', '2026-05-11 19:34:09', '[\"등을 대고 팔과 다리를 펴고 눕습니다.\",\"동시에 상체와 다리를 올립니다.\",\"손이 발에 닿도록 합니다.\",\"복근이 완전히 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240090, 'Dragon Flag', '드래곤 플래그', 'abs', 'bodyweight', 'strength', 'advanced', 'Advanced core exercise popularized by Bruce Lee.', '브루스 리가 대중화한 고급 코어 운동입니다.', '[\"rectus abdominis\",\"core\"]', '[\"lats\",\"glutes\"]', NULL, '[]', '[\"Lie on bench holding behind head\",\"Raise body to vertical\",\"Lower slowly keeping body straight\",\"Stop before touching bench\"]', '2026-05-11 19:34:09', '[\"벤치에 누워 머리 위 벤치를 잡습니다.\",\"몸을 수직으로 들어 올립니다.\",\"몸을 일직선으로 유지하며 천천히 내립니다.\",\"벤치에 닿기 직전에 멈춥니다.\",\"다시 올리며 반복합니다.\"]'),
(240091, 'Seated Forward Fold', '앉아서 앞으로 굽히기', 'stretching', 'none', 'flexibility', 'beginner', 'Full posterior chain stretch seated.', '앉아서 하는 전체 후면 근육 스트레칭입니다.', '[\"hamstrings\",\"lower back\"]', '[\"calves\"]', NULL, '[]', '[\"Sit with legs extended\",\"Hinge forward from hips\",\"Reach toward feet\",\"Hold 60 seconds\"]', '2026-05-11 19:34:09', '[\"바닥에 앉아 다리를 앞으로 펍니다.\",\"엉덩이를 뒤로 빼며 상체를 앞으로 숙입니다.\",\"손이 발 쪽으로 향하도록 합니다.\",\"후면 근육 전체가 늘어나는 것을 느낍니다.\",\"60초간 유지합니다.\"]'),
(240092, 'Spinal Twist', '척추 비틀기', 'stretching', 'none', 'flexibility', 'beginner', 'Lying spinal rotation for back mobility.', '등 가동성을 위한 누워서 하는 척추 회전입니다.', '[\"spine\",\"obliques\"]', '[\"glutes\",\"IT band\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Lie on back\",\"Bring knee across body\",\"Extend arm opposite direction\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:10', '[\"등을 대고 눕습니다.\",\"한쪽 무릎을 반대쪽으로 넘깁니다.\",\"반대 팔을 옆으로 뻗습니다.\",\"척추가 회전되는 것을 느낍니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240093, 'Doorway Shoulder Stretch', '문틀 어깨 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Anterior shoulder and chest stretch in doorway.', '문틀에서 하는 전면 어깨와 가슴 스트레칭입니다.', '[\"anterior deltoid\",\"pectoralis minor\"]', '[\"biceps\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Stand in doorway\",\"Place arm at 90 degrees on frame\",\"Lean forward gently\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:10', '[\"문틀 앞에 서서 팔을 90도로 구부립니다.\",\"팔꿈치를 문틀에 올립니다.\",\"몸을 앞으로 기울입니다.\",\"전면 어깨와 가슴이 늘어나는 것을 느낍니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240094, 'Neck Stretch', '목 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Gentle neck mobility exercise.', '부드러운 목 가동성 운동입니다.', '[\"neck\",\"upper trapezius\"]', '[]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Sit or stand tall\",\"Tilt head to one side\",\"Gently pull with hand\",\"Hold 30 seconds each side\"]', '2026-05-11 19:34:10', '[\"바르게 앉거나 섭니다.\",\"머리를 한쪽으로 기울입니다.\",\"같은 쪽 손으로 머리를 가볍게 당깁니다.\",\"목 옆 근육이 늘어나는 것을 느낍니다.\",\"30초간 유지 후 반대쪽으로 반복합니다.\"]'),
(240095, 'Butterfly Stretch', '나비 스트레칭', 'stretching', 'none', 'flexibility', 'beginner', 'Inner thigh and groin stretch.', '내전근과 사타구니 스트레칭입니다.', '[\"inner thighs\",\"groin\"]', '[\"hip flexors\"]', NULL, '[]', '[\"Sit with soles of feet together\",\"Hold feet with hands\",\"Press knees toward floor\",\"Hold 60 seconds\"]', '2026-05-11 19:34:10', '[\"바닥에 앉아 발바닥을 서로 붙입니다.\",\"양손으로 발을 잡습니다.\",\"무릎을 바닥 쪽으로 누릅니다.\",\"내전근이 늘어나는 것을 느낍니다.\",\"60초간 유지합니다.\"]'),
(240096, 'Downward Dog', '다운워드 독', 'stretching', 'none', 'flexibility', 'beginner', 'Yoga pose stretching hamstrings and calves.', '햄스트링과 종아리를 스트레칭하는 요가 자세입니다.', '[\"hamstrings\",\"calves\"]', '[\"shoulders\",\"back\"]', NULL, '[]', '[\"Start on hands and knees\",\"Push hips up and back\",\"Straighten legs\",\"Press heels toward floor\"]', '2026-05-11 19:34:11', '[\"네발 기기 자세에서 시작합니다.\",\"엉덩이를 위로 들어 올립니다.\",\"다리를 최대한 펍니다.\",\"발뒤꿈치를 바닥 쪽으로 누릅니다.\",\"햄스트링과 종아리가 늘어나는 것을 느낍니다.\"]'),
(240097, 'World\'s Greatest Stretch', '세계 최고의 스트레칭', 'stretching', 'none', 'flexibility', 'intermediate', 'Multi-joint mobility exercise.', '다관절 가동성 운동입니다.', '[\"hip flexors\",\"thoracic spine\",\"hamstrings\"]', '[\"shoulders\",\"groin\"]', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F0.jpg', '[\"https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Stretch%2F1.jpg\"]', '[\"Start in lunge position\",\"Place hand inside front foot\",\"Rotate upper body up\",\"Reach arm to ceiling\"]', '2026-05-11 19:34:11', '[\"런지 자세를 취합니다.\",\"앞발 안쪽에 손을 놓습니다.\",\"상체를 회전하며 팔을 천장 쪽으로 뻗습니다.\",\"전신의 여러 근육이 늘어나는 것을 느낍니다.\",\"반대쪽으로 반복합니다.\"]'),
(240098, 'Battle Ropes', '배틀 로프', 'full_body', 'none', 'cardio', 'intermediate', 'High intensity conditioning with battle ropes.', '배틀 로프를 이용한 고강도 컨디셔닝 운동입니다.', '[\"shoulders\",\"arms\",\"core\"]', '[\"legs\",\"back\"]', NULL, '[]', '[\"Hold rope ends\",\"Create waves alternately\",\"Keep core tight\",\"Maintain for set time\"]', '2026-05-11 19:34:11', '[\"로프 끝을 양손에 잡습니다.\",\"무릎을 약간 구부리고 코어를 단단히 유지합니다.\",\"번갈아가며 파도를 만들듯 로프를 움직입니다.\",\"일정한 리듬을 유지합니다.\",\"목표 시간만큼 반복합니다.\"]'),
(240099, 'Farmer\'s Walk', '파머스 워크', 'full_body', 'dumbbell', 'strength', 'beginner', 'Loaded carry for grip and core strength.', '그립력과 코어 힘을 위한 무게 들고 걷기 운동입니다.', '[\"forearms\",\"core\",\"trapezius\"]', '[\"legs\",\"shoulders\"]', NULL, '[]', '[\"Hold heavy dumbbells at sides\",\"Walk with upright posture\",\"Keep core braced\",\"Set down with control\"]', '2026-05-11 19:34:11', '[\"무거운 덤벨을 양손에 듭니다.\",\"상체를 수직으로 유지하며 걷습니다.\",\"코어를 단단히 유지합니다.\",\"목표 거리 또는 시간만큼 걷습니다.\",\"덤벨을 조심스럽게 내려놓습니다.\"]'),
(240100, 'Sled Push', '슬레드 푸시', 'full_body', 'machine', 'cardio', 'intermediate', 'Pushing weighted sled for conditioning.', '컨디셔닝을 위한 무게 슬레드 밀기 운동입니다.', '[\"quadriceps\",\"glutes\"]', '[\"shoulders\",\"core\"]', NULL, '[]', '[\"Grip sled handles\",\"Lean forward and drive legs\",\"Push sled across floor\",\"Maintain low position\"]', '2026-05-11 19:34:12', '[\"슬레드 핸들을 잡습니다.\",\"상체를 앞으로 기울이며 다리로 밀어냅니다.\",\"낮은 자세를 유지합니다.\",\"목표 거리만큼 슬레드를 밉니다.\",\"코어를 단단히 유지합니다.\"]');

INSERT INTO `exercises` (`id`, `name`, `nameKo`, `bodyPart`, `equipment`, `category`, `difficulty`, `description`, `descriptionKo`, `primaryMuscles`, `secondaryMuscles`, `gifUrl`, `secondaryImages`, `instructions`, `createdAt`, `instructionsKo`) VALUES
(240101, 'Cable Kickback', '케이블 킥백', 'glutes', 'cable', 'hypertrophy', 'beginner', 'Cable exercise for glute isolation.', '둔근 고립을 위한 케이블 운동입니다.', '[\"glutes\"]', '[\"hamstrings\"]', NULL, '[]', '[\"Attach ankle strap to cable\",\"Face cable machine\",\"Kick leg back and up\",\"Squeeze glute at top\"]', '2026-05-11 19:34:12', '[\"발목에 케이블 스트랩을 연결합니다.\",\"케이블 머신을 마주 보고 섭니다.\",\"다리를 뒤로 들어 올립니다.\",\"둔근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\"]'),
(240102, 'Donkey Kick', '당나귀 킥', 'glutes', 'bodyweight', 'hypertrophy', 'beginner', 'Bodyweight glute exercise on all fours.', '네발 기기 자세로 하는 맨몸 둔근 운동입니다.', '[\"glutes\"]', '[\"hamstrings\",\"core\"]', NULL, '[]', '[\"Start on hands and knees\",\"Kick one leg up and back\",\"Squeeze glute at top\",\"Lower and repeat\"]', '2026-05-11 19:34:12', '[\"네발 기기 자세를 취합니다.\",\"한 다리를 뒤로 들어 올립니다.\",\"둔근이 수축되는 것을 느낍니다.\",\"천천히 내리며 반복합니다.\",\"반대 다리로 반복합니다.\"]'),
(240103, 'Abductor Machine', '어브덕터 머신', 'glutes', 'machine', 'hypertrophy', 'beginner', 'Machine exercise for hip abductors.', '고관절 외전근을 위한 머신 운동입니다.', '[\"hip abductors\",\"glute medius\"]', '[]', NULL, '[]', '[\"Sit in abductor machine\",\"Push legs outward\",\"Hold briefly\",\"Return slowly\"]', '2026-05-11 19:34:12', '[\"어브덕터 머신에 앉아 패드를 허벅지 바깥쪽에 위치시킵니다.\",\"다리를 바깥쪽으로 밀어 냅니다.\",\"고관절 외전근이 수축되는 것을 느낍니다.\",\"천천히 원래 위치로 돌아옵니다.\",\"반복합니다.\"]');

DROP TABLE IF EXISTS `routine_exercises`;
CREATE TABLE `routine_exercises` (
  `id` int NOT NULL AUTO_INCREMENT,
  `routineId` int NOT NULL,
  `exerciseId` int NOT NULL,
  `order` int NOT NULL,
  `sets` int DEFAULT '3',
  `reps` int DEFAULT '10',
  `restSeconds` int DEFAULT '90',
  `notes` text DEFAULT NULL,
  `weightKg` float DEFAULT NULL,
  `setDetails` json DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=150001;

DROP TABLE IF EXISTS `routines`;
CREATE TABLE `routines` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `goal` enum('hypertrophy','fat_loss','strength','endurance','flexibility','general') NOT NULL,
  `daysPerWeek` int DEFAULT '3',
  `isPublic` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=150001;

INSERT INTO `routines` (`id`, `userId`, `name`, `description`, `goal`, `daysPerWeek`, `isPublic`, `createdAt`, `updatedAt`) VALUES
(120001, 1, '가슴삼두어깨', '', 'hypertrophy', 1, 0, '2026-05-11 21:49:08', '2026-05-11 21:49:08');

DROP TABLE IF EXISTS `user_goals`;
CREATE TABLE `user_goals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `goal` enum('hypertrophy','fat_loss','strength','endurance','flexibility','general') NOT NULL,
  `targetWeight` float DEFAULT NULL,
  `weeklyWorkouts` int DEFAULT '3',
  `isActive` tinyint(1) NOT NULL DEFAULT '1',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `heightCm` float DEFAULT NULL,
  `gender` enum('male','female') DEFAULT NULL,
  `birthYear` int DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=210001;

INSERT INTO `user_goals` (`id`, `userId`, `goal`, `targetWeight`, `weeklyWorkouts`, `isActive`, `createdAt`, `updatedAt`, `heightCm`, `gender`, `birthYear`) VALUES
(150001, 1, 'hypertrophy', NULL, 4, 0, '2026-05-11 20:55:28', '2026-05-11 21:51:27', NULL, NULL, NULL),
(180001, 1, 'hypertrophy', NULL, 4, 1, '2026-05-11 21:51:27', '2026-05-11 21:51:27', NULL, NULL, NULL);

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `openId` varchar(64) NOT NULL,
  `name` text DEFAULT NULL,
  `email` varchar(320) DEFAULT NULL,
  `loginMethod` varchar(64) DEFAULT NULL,
  `role` enum('user','admin') NOT NULL DEFAULT 'user',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastSignedIn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `users_openId_unique` (`openId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2550001;

INSERT INTO `users` (`id`, `openId`, `name`, `email`, `loginMethod`, `role`, `createdAt`, `updatedAt`, `lastSignedIn`) VALUES
(1, 'jw8BqmJgrV4ZaLxQEbdN2q', '현일 최', 'gusdlfboy@gmail.com', 'google', 'admin', '2026-05-10 17:23:00', '2026-05-13 19:27:57', '2026-05-13 19:27:57');

DROP TABLE IF EXISTS `workout_logs`;
CREATE TABLE `workout_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sessionId` int NOT NULL,
  `exerciseId` int NOT NULL,
  `setNumber` int NOT NULL,
  `reps` int DEFAULT NULL,
  `weightKg` float DEFAULT NULL,
  `durationSeconds` int DEFAULT NULL,
  `distanceM` float DEFAULT NULL,
  `isWarmup` tinyint(1) NOT NULL DEFAULT '0',
  `notes` text DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rpe` tinyint DEFAULT NULL,
  `memo` text DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001;

DROP TABLE IF EXISTS `workout_sessions`;
CREATE TABLE `workout_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int NOT NULL,
  `routineId` int DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL,
  `startedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` timestamp NULL DEFAULT NULL,
  `durationMinutes` int DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `totalVolume` float DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `workoutDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=210001;

INSERT INTO `workout_sessions` (`id`, `userId`, `routineId`, `name`, `startedAt`, `completedAt`, `durationMinutes`, `notes`, `totalVolume`, `createdAt`, `workoutDate`) VALUES
(180003, 1, NULL, '오늘의 상체 운동', '2026-05-12 16:46:18', NULL, NULL, NULL, NULL, '2026-05-12 16:46:18', '2026-05-12 17:17:18'),
(180004, 1, NULL, NULL, '2026-05-12 16:46:19', NULL, NULL, NULL, NULL, '2026-05-12 16:46:18', '2026-05-12 17:17:18'),
(180010, 1, NULL, '아침 운동', '2026-05-12 16:46:27', NULL, NULL, NULL, NULL, '2026-05-12 16:46:27', '2026-05-12 17:17:18'),
(180011, 1, NULL, '저녁 운동', '2026-05-12 16:46:27', NULL, NULL, NULL, NULL, '2026-05-12 16:46:27', '2026-05-12 17:17:18'),
(180016, 1, NULL, '오늘의 상체 운동', '2026-05-12 16:46:50', NULL, NULL, NULL, NULL, '2026-05-12 16:46:50', '2026-05-12 17:17:18'),
(180017, 1, NULL, NULL, '2026-05-12 16:46:50', NULL, NULL, NULL, NULL, '2026-05-12 16:46:50', '2026-05-12 17:17:18'),
(180023, 1, NULL, '아침 운동', '2026-05-12 16:46:58', NULL, NULL, NULL, NULL, '2026-05-12 16:46:58', '2026-05-12 17:17:18'),
(180024, 1, NULL, '저녁 운동', '2026-05-12 16:46:58', NULL, NULL, NULL, NULL, '2026-05-12 16:46:58', '2026-05-12 17:17:18');

SET FOREIGN_KEY_CHECKS=1;
