BEGIN;

DROP TABLE IF EXISTS workout_logs;
DROP TABLE IF EXISTS workout_sessions;
DROP TABLE IF EXISTS routine_exercises;
DROP TABLE IF EXISTS routines;
DROP TABLE IF EXISTS user_goals;
DROP TABLE IF EXISTS exercise_favorites;
DROP TABLE IF EXISTS exercise_goals;
DROP TABLE IF EXISTS body_weights;
DROP TABLE IF EXISTS exercises;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role text NOT NULL DEFAULT 'user',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "lastSignedIn" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE exercises (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  "nameKo" varchar(200) NOT NULL,
  "bodyPart" text NOT NULL,
  equipment text NOT NULL,
  category text NOT NULL,
  difficulty text NOT NULL,
  description text,
  "descriptionKo" text,
  "primaryMuscles" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "secondaryMuscles" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "gifUrl" text,
  "secondaryImages" jsonb DEFAULT '[]'::jsonb,
  instructions jsonb NOT NULL DEFAULT '[]'::jsonb,
  "instructionsKo" jsonb,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_goals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  goal text NOT NULL,
  "targetWeight" double precision,
  "weeklyWorkouts" integer DEFAULT 3,
  "heightCm" double precision,
  gender text,
  "birthYear" integer,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE routines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  name varchar(200) NOT NULL,
  description text,
  goal text NOT NULL,
  "daysPerWeek" integer DEFAULT 3,
  "isPublic" boolean NOT NULL DEFAULT false,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE routine_exercises (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "routineId" integer NOT NULL,
  "exerciseId" integer NOT NULL,
  "order" integer NOT NULL,
  sets integer DEFAULT 3,
  reps integer DEFAULT 10,
  "weightKg" double precision,
  "restSeconds" integer DEFAULT 90,
  "setDetails" jsonb DEFAULT '[]'::jsonb,
  notes text
);

CREATE TABLE workout_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "routineId" integer,
  name varchar(200),
  "startedAt" timestamptz NOT NULL DEFAULT now(),
  "completedAt" timestamptz,
  "durationMinutes" integer,
  notes text,
  "totalVolume" double precision,
  "workoutDate" timestamptz NOT NULL DEFAULT now(),
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE workout_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessionId" integer NOT NULL,
  "exerciseId" integer NOT NULL,
  "setNumber" integer NOT NULL,
  reps integer,
  "weightKg" double precision,
  "durationSeconds" integer,
  "distanceM" double precision,
  "isWarmup" boolean NOT NULL DEFAULT false,
  rpe integer,
  memo text,
  notes text,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE exercise_favorites (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "exerciseId" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE body_weights (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "weightKg" double precision NOT NULL,
  "bodyFatPct" double precision,
  "muscleMassPct" double precision,
  notes text,
  "recordedAt" timestamptz NOT NULL DEFAULT now(),
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE exercise_goals (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "exerciseId" integer NOT NULL,
  "targetWeightKg" double precision,
  "targetReps" integer,
  notes text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_exercises_name_ko ON exercises ("nameKo");
CREATE INDEX idx_user_goals_user ON user_goals ("userId");
CREATE INDEX idx_routines_user ON routines ("userId");
CREATE INDEX idx_routine_exercises_routine ON routine_exercises ("routineId");
CREATE INDEX idx_workout_sessions_user_date ON workout_sessions ("userId", "workoutDate");
CREATE INDEX idx_workout_logs_session ON workout_logs ("sessionId");
CREATE INDEX idx_exercise_favorites_user ON exercise_favorites ("userId");
CREATE INDEX idx_body_weights_user_recorded ON body_weights ("userId", "recordedAt");
CREATE INDEX idx_exercise_goals_user_exercise ON exercise_goals ("userId", "exerciseId");

COMMIT;
